// Code generated by a calibration fixture script. DO NOT EDIT.

// Package generated is a calibration fixture: a file carrying the standard
// generated-code header is skipped entirely, because nobody edits it by hand —
// the fix belongs in the generator.
package generated

import "io/ioutil"

func init() {}

// Dump prints whatever it receives.
func Dump(v interface{}) {
	fmt.Println(v.(string), os.Getenv("DEBUG"))
	_, _ = ioutil.ReadAll(nil)
}
